version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - sbs44
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: daily
      time: "01:00"
      timezone: "America/New_York"
    cooldown:
      default-days: 3

  - package-ecosystem: npm
    directory: /
    assignees:
      - sbs44
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: weekly
      day: monday
      time: "01:00"
      timezone: "America/New_York"
    cooldown:
      default-days: 7
      semver-major-days: 14
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
