// @generated by expo-module-scripts
const { defineConfig } = require('eslint/config');
const universeWebConfig = require('eslint-config-universe/flat/web');
const baseConfig = require('expo-module-scripts/eslint.config.base');
const globals = require('globals');

module.exports = defineConfig([
  { ignores: ['build/', 'plugin/build/'] },
  baseConfig,
  { extends: universeWebConfig },
  {
    files: ['example/*.config.js'],
    languageOptions: {
      globals: globals.node,
    },
  },
]);
