import {
  type ConfigPlugin,
  withDangerousMod,
  withInfoPlist,
  withXcodeProject,
} from 'expo/config-plugins';
import fs from 'fs';
import path from 'path';

/**
 * CarPlay requires UIApplicationSceneManifest in Info.plist, which forces iOS
 * to adopt scene lifecycle for the entire app. Expo's AppDelegate creates its
 * window in didFinishLaunchingWithOptions using UIWindow(frame:), which isn't
 * associated with a scene — so the phone screen goes black.
 *
 * We fix this by:
 * 1. Declaring both a phone scene and CarPlay scene in Info.plist
 * 2. Writing a PhoneSceneDelegate.swift that takes AppDelegate's existing
 *    window and assigns it to the window scene
 * 3. Adding the file to the Xcode project so it gets compiled
 */
export const withCarPlayInfoPlist: ConfigPlugin = config => {
  config = withSceneManifest(config);
  config = withPhoneSceneDelegateFile(config);
  config = withPhoneSceneDelegateXcodeRef(config);
  return config;
};

// 1. Add both phone and CarPlay scenes to Info.plist
const withSceneManifest: ConfigPlugin = config => {
  return withInfoPlist(config, config => {
    const manifest: any = config.modResults.UIApplicationSceneManifest ?? {};
    const configs: any = manifest.UISceneConfigurations ?? {};

    configs.UIWindowSceneSessionRoleApplication = [
      {
        UISceneClassName: 'UIWindowScene',
        UISceneConfigurationName: 'Default Configuration',
        UISceneDelegateClassName: 'PhoneSceneDelegate',
      },
    ];
    configs.CPTemplateApplicationSceneSessionRoleApplication = [
      {
        UISceneClassName: 'CPTemplateApplicationScene',
        UISceneConfigurationName: 'CarPlay',
        UISceneDelegateClassName: 'ExpoCarPlay.CarPlaySceneDelegate',
      },
    ];

    manifest.UISceneConfigurations = configs;
    config.modResults.UIApplicationSceneManifest = manifest;
    return config;
  });
};

// 2. Write PhoneSceneDelegate.swift into the app's ios source directory
const withPhoneSceneDelegateFile: ConfigPlugin = config => {
  return withDangerousMod(config, [
    'ios',
    config => {
      const appDir = findAppSourceDir(config.modRequest.platformProjectRoot);
      if (!appDir) {
        throw new Error(
          'expo-carplay: Could not find app source directory in ios/'
        );
      }

      const filePath = path.join(appDir, 'PhoneSceneDelegate.swift');

      fs.writeFileSync(filePath, PHONE_SCENE_DELEGATE_SOURCE, 'utf8');

      return config;
    },
  ]);
};

// 3. Add PhoneSceneDelegate.swift to the Xcode project's compile sources
const withPhoneSceneDelegateXcodeRef: ConfigPlugin = config => {
  return withXcodeProject(config, config => {
    const project = config.modResults;
    const projectName = config.modRequest.projectName;
    if (!projectName) {
      throw new Error('expo-carplay: Could not determine Xcode project name');
    }

    const filePath = `${projectName}/PhoneSceneDelegate.swift`;

    if (!project.hasFile(filePath)) {
      const groupKey = project.findPBXGroupKey({ name: projectName });
      if (!groupKey) {
        throw new Error(
          `expo-carplay: Could not find PBXGroup "${projectName}" in Xcode project`
        );
      }
      project.addSourceFile(filePath, {}, groupKey);
    }

    return config;
  });
};

/**
 * Find the app source directory (the one containing AppDelegate.swift).
 */
function findAppSourceDir(platformProjectRoot: string): string | null {
  const entries = fs.readdirSync(platformProjectRoot, {
    withFileTypes: true,
  });
  for (const entry of entries) {
    if (
      entry.isDirectory() &&
      !entry.name.startsWith('.') &&
      entry.name !== 'Pods' &&
      entry.name !== 'build'
    ) {
      const candidate = path.join(
        platformProjectRoot,
        entry.name,
        'AppDelegate.swift'
      );
      if (fs.existsSync(candidate)) {
        return path.join(platformProjectRoot, entry.name);
      }
    }
  }
  return null;
}

const PHONE_SCENE_DELEGATE_SOURCE = `import UIKit

// Auto-generated by expo-carplay.
// Bridges Expo's AppDelegate-based window to iOS scene lifecycle,
// which is required when UIApplicationSceneManifest is present for CarPlay.
@objc(PhoneSceneDelegate)
class PhoneSceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = UIApplication.shared.delegate,
          let window = appDelegate.window
    else { return }
    window.windowScene = windowScene
    self.window = window
  }
}
`;
